POST http://localhost:8788/stats
Content-Type: application/json

{
    "hintsRemaining": 3,
    "timeTaken": 1000,
    "streak": 1,
    "maxStreak": 1
}

### 

GET https://linkagram.jasoncabot.me/stats