name = "linkagram"
compatibility_date = "2022-12-24"
pages_build_output_dir = "dist"

[[services]]
binding = "IMAGE_GENERATOR"
service = "linkagram-img"

[[services]]
binding = "PAYMENT_SERVICE"
service = "linkagram-pay"

[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "completions"

[[kv_namespaces]]
binding = "SUGGESTIONS"
id = "a76e8697af2b455ea90c010124904f80"

[[kv_namespaces]]
binding = "DEFINITIONS"
id = "cdba59d73ef0469bb8906b7220b2f801"

[vars]
ACCOUNT_ID = "account_id"
API_TOKEN = "api_token"
