name = "linkagram"
compatibility_date = "2022-12-24"

[[services]]
binding = "IMAGE_GENERATOR"
service = "linkagram-img"

[[services]]
binding = "PAYMENT_SERVICE"
service = "linkagram-pay"

[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "completions"

[vars]
ACCOUNT_ID = "account_id"
API_TOKEN = "api_token"
